cart/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('cart.views',
    url(r'^$', 'index', name='index'),
)

order/urls.py
from django.conf.urls import patterns, url, include

TOKEN_PATTERN = ('(?P<token>[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}'
                 '-[0-9a-z]{12})')

urlpatterns = patterns('order.views',
    url(r'^%s/$' % TOKEN_PATTERN, 'details', name='details'),
    url(r'^%s/success/$' % TOKEN_PATTERN, 'success', name='success'),
    url(r'^%s/' % TOKEN_PATTERN, include('payment.urls', namespace='payment'))
)

registration/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^login/$', 'registration.views.login', name='login'),
    url(r'^logout/$', 'registration.views.logout', name='logout'),
    url(r'^oauth_callback/(?P<service>\w+)/$',
        'registration.views.oauth_callback',
        name='oauth_callback'),
    url(r'^change_password/$',
        'registration.views.change_password',
        name='change_password'),
    url(r'^request_email_confirmation/$',
        'registration.views.request_email_confirmation',
        name='request_email_confirmation'),
    url(r'^confirm_email/(?P<token>\w+)/$',
        'registration.views.confirm_email',
        name='confirm_email'),
    url(r'^request_email_change/$',
        'registration.views.request_email_change',
        name='request_email_change'),
    url(r'^change_email/(?P<token>\w+)/$',
        'registration.views.change_email',
        name='change_email'))

saleor/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'saleor.views.home', name='home'),
    url(r'^products/', include('product.urls', namespace='product')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^account/', include('registration.urls', namespace='registration')),
    url(r'^profile/', include('userprofile.urls', namespace='profile')),
    url(r'^', include('payments.urls')),
)

userprofile/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^$', 'userprofile.views.details', name='details'),
    url(r'^orders/$', 'userprofile.views.orders', name='orders'),
    url(r'^address/create/$',
        'userprofile.views.address_create',
        name='address-create'),
    url(r'^address/(?P<slug>[\w-]+)-(?P<pk>\d+)/edit/$',
        'userprofile.views.address_edit',
        name='address-edit'),
    url(r'^address/(?P<slug>[\w-]+)-(?P<pk>\d+)/delete/$',
        'userprofile.views.address_delete',
        name='address-delete'),
    url(r'^address/(?P<pk>\d+)/make-default-for-'
        '(?P<purpose>billing|shipping)/$',
        'userprofile.views.address_make_default',
        name='address-make-default'))

saleor/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base.html')

saleor/templates/base.html
{% load i18n %}
{% load categories_list from category %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% trans "Sale or" %}...!{% endblock %}</title>
        {% block meta %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        <meta name="author" content="{% trans "Mirumee Software" %}">
        {% endblock meta %}

        {% if debug %}
        <link rel="stylesheet/less" type="text/css" href="{{ STATIC_URL }}less/style.less">
        {% else %}
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css">
        {% endif %}

        {% block stylesheet %}{% endblock stylesheet %}

        {% if debug %}
        <script type="text/javascript" src="{{ STATIC_URL }}js/lib/less.js"></script>
        {% endif %}
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>

    <body itemscope itemtype="http://schema.org/WebPage">
        <header class="navbar navbar-inverse navbar-static-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="/">Saleor</a>
                    <nav class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active">
                                <a href="/">Home</a>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#"> {% trans "Categories" %} <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    {% categories_list %}
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="{% url "cart:index" %}">{{ request.cart }} <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    {% for cart_line in request.cart %}
                                    <li><a href="{{ cart_line.product.get_absolute_url }}">{{ cart_line.product }} ({{ cart_line.quantity }})</a></li>
                                    {% endfor %}
                                    <li><a href="{% url "checkout:index" %}">Checkout</a></li>
                                    <li><a href="{% url "cart:index" %}">Cart</a></li>
                                  </ul>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="dropdown pull-right"> {# TODO pull-right not working #}
                                <a data-toggle="dropdown" class="dropdown-toggle" href=".">{{ user }} <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url "profile:details" %}">{% trans "Your profile" %}</a></li>
                                    <li><a href="{% url "profile:orders" %}">{% trans "Your orders" %}</a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url "registration:logout" %}">{% trans "Log out" %}</a></li>
                                  </ul>
                            </li>
                            {% else %}
                            <li>
                                <a href="{% url "registration:login" %}">Log in</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        {% if messages %}
        <div class="container">
            {% for message in messages %}
            <div class="row alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
            {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="container">
            <div class="row">
                {% block outerbreadcrumb %}
                <ul class="breadcrumb" itemprop="breadcrumb">
                    {% block breadcrumb %}
                    <li>
                        <a href="/">{% trans "Home" %}</a> <span class="divider">/</span>
                    </li>
                    {% endblock breadcrumb %}
                </ul>
                {% endblock outerbreadcrumb %}
            </div>
            {% block outercontent %}
            <div class="row">

                {% block content %}
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tempor ornare neque et consequat. Vestibulum euismod, ante mollis luctus tincidunt, ligula lorem tempor libero, sed molestie nisi lectus id dolor. Sed pharetra tempor hendrerit. Duis condimentum hendrerit libero eget rutrum. Duis facilisis placerat purus ut tincidunt. Fusce sit amet diam eu ante posuere semper. Curabitur vehicula, mauris non volutpat gravida, urna mauris rutrum erat, convallis commodo arcu quam ac nunc. Pellentesque mattis rutrum ornare. Etiam sed suscipit nunc. Maecenas malesuada metus dapibus nibh lobortis non rutrum tellus facilisis. Fusce a urna in lacus ultricies adipiscing non ut leo.
                </p>
                <p>
                    Sed a dolor diam, viverra vestibulum diam. Morbi scelerisque metus ut erat vehicula bibendum euismod lacus lacinia. Pellentesque risus nisi, dignissim nec rutrum id, vehicula ac libero. Vivamus pulvinar varius ante, ac sollicitudin sapien luctus vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla volutpat velit eu augue tincidunt id volutpat lectus ullamcorper. Cras interdum leo sed nisi tincidunt non mattis nulla facilisis.
                </p>
                <p>
                    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed mauris diam, fermentum vitae convallis eu, varius in magna. Aenean pretium aliquam sodales. Cras sapien augue, ornare sit amet consequat sit amet, viverra et mi. Integer id metus odio. Nunc in venenatis metus. Nullam porta aliquam diam, at imperdiet tellus pharetra a. Mauris dapibus tristique fringilla. Vestibulum ipsum arcu, rhoncus dictum adipiscing in, pretium a est.
                </p>
                <p>
                    Integer cursus est a purus tristique nec porta erat condimentum. In ornare neque non dolor mollis elementum. Nunc eu lectus non dolor commodo porta ac vel urna. Quisque vel nibh non risus congue lobortis non at eros. Duis non leo magna. Nunc malesuada, quam ut dapibus aliquet, nisi justo eleifend lectus, ac venenatis ante tellus quis mauris. Integer tincidunt enim nec mi accumsan vitae ultricies purus vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
                </p>
                <p>
                    Duis pellentesque dolor arcu, id cursus nisl. Praesent et congue purus. Cras pulvinar posuere libero, at molestie orci lobortis in. Pellentesque et tellus et magna faucibus laoreet. Integer tempor velit ac enim congue sit amet semper lorem sodales. Curabitur sed sem magna, id aliquet nisi. Curabitur eu magna metus. Duis pellentesque, libero quis fringilla tincidunt, magna mauris egestas nunc, eu iaculis augue enim at orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas sit amet suscipit odio. Phasellus ut sem a urna adipiscing lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non dui a urna pharetra ullamcorper in eget turpis. Donec a dui sapien. In tristique condimentum arcu aliquet laoreet.
                </p>
                {% endblock content %}
            </div>
            {% endblock outercontent %}

            <footer>
                <p class="pull-right">
                    &copy; Mirumee Labs 2013
                </p>
            </footer>
        </div>
        {% block third-party-js %}
        {% if GOOGLE_ANALYTICS_CODE %}
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','__ga');
        {% block google-analytics-script %}
          __ga('create', '{{ GOOGLE_ANALYTICS_CODE }}', '{{ CANONICAL_HOSTNAME }}');
          __ga('send', 'pageview');
        {% endblock google-analytics-script %}
        </script>
        {% endif %}
        {% endblock third-party-js %}
        {% block footer_scripts %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="//twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
        <script src="//twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js"></script>
        <script src="//twitter.github.com/bootstrap/assets/js/bootstrap-popover.js"></script>
        {% endblock footer_scripts %}
    </body>
</html>