cart/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('cart.views',
    url(r'^$', 'index', name='index'),
)

order/urls.py
from django.conf.urls import patterns, url, include

TOKEN_PATTERN = ('(?P<token>[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}'
                 '-[0-9a-z]{12})')

urlpatterns = patterns('order.views',
    url(r'^%s/$' % TOKEN_PATTERN, 'details', name='details'),
    url(r'^%s/success/$' % TOKEN_PATTERN, 'success', name='success'),
    url(r'^%s/' % TOKEN_PATTERN, include('payment.urls', namespace='payment'))
)

registration/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^login/$', 'registration.views.login', name='login'),
    url(r'^logout/$', 'registration.views.logout', name='logout'),
    url(r'^oauth_callback/(?P<service>\w+)/$',
        'registration.views.oauth_callback',
        name='oauth_callback'),
    url(r'^change_password/$',
        'registration.views.change_password',
        name='change_password'),
    url(r'^request_email_confirmation/$',
        'registration.views.request_email_confirmation',
        name='request_email_confirmation'),
    url(r'^confirm_email/(?P<token>\w+)/$',
        'registration.views.confirm_email',
        name='confirm_email'),
    url(r'^request_email_change/$',
        'registration.views.request_email_change',
        name='request_email_change'),
    url(r'^change_email/(?P<token>\w+)/$',
        'registration.views.change_email',
        name='change_email'))

saleor/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'saleor.views.home', name='home'),
    url(r'^products/', include('product.urls', namespace='product')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^account/', include('registration.urls', namespace='registration')),
    url(r'^profile/', include('userprofile.urls', namespace='profile')),
    url(r'^', include('payments.urls')),
)

userprofile/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^$', 'userprofile.views.details', name='details'),
    url(r'^orders/$', 'userprofile.views.orders', name='orders'),
    url(r'^address/create/$',
        'userprofile.views.address_create',
        name='address-create'),
    url(r'^address/(?P<slug>[\w-]+)-(?P<pk>\d+)/edit/$',
        'userprofile.views.address_edit',
        name='address-edit'),
    url(r'^address/(?P<slug>[\w-]+)-(?P<pk>\d+)/delete/$',
        'userprofile.views.address_delete',
        name='address-delete'),
    url(r'^address/(?P<pk>\d+)/make-default-for-'
        '(?P<purpose>billing|shipping)/$',
        'userprofile.views.address_make_default',
        name='address-make-default'))

order/models.py
from communication.mail import send_email
from decimal import Decimal
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import pgettext_lazy
from django_prices.models import PriceField
from prices import Price
from product.models import Product, Subtyped
from saleor.utils import build_absolute_uri
from satchless.item import ItemSet, ItemLine
from userprofile.models import Address
from uuid import uuid4
import datetime


class Order(models.Model, ItemSet):

    STATUS_CHOICES = (
        ('new', pgettext_lazy(u'Order status field value', u'New')),
        ('cancelled', pgettext_lazy(u'Order status field value',
                                    u'Cancelled')),
        ('payment-pending', pgettext_lazy(u'Order status field value',
                                          u'Waiting for payment')),
        ('fully-paid', pgettext_lazy(u'Order status field value',
                                     u'Fully paid')),
        ('shipped', pgettext_lazy(u'Order status field value',
                                  u'Shipped')))
    status = models.CharField(
        pgettext_lazy(u'Order field', u'order status'),
        max_length=32, choices=STATUS_CHOICES, default='new')
    created = models.DateTimeField(
        pgettext_lazy(u'Order field', u'created'),
        default=datetime.datetime.now, editable=False)
    last_status_change = models.DateTimeField(
        pgettext_lazy(u'Order field', u'last status change'),
        default=datetime.datetime.now, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='orders',
        verbose_name=pgettext_lazy(u'Order field', u'user'))
    billing_address = models.ForeignKey(Address, related_name='+')
    anonymous_user_email = models.EmailField(blank=True, default='')
    token = models.CharField(
        pgettext_lazy(u'Order field', u'token'),
        max_length=36, blank=True, default='')

    class Meta:
        ordering = ('-last_status_change',)

    def save(self, *args, **kwargs):
        if not self.token:
            for _i in xrange(100):
                token = str(uuid4())
                if not type(self).objects.filter(token=token).exists():
                    self.token = token
                    break
        return super(Order, self).save(*args, **kwargs)

    def change_status(self, status):
        self.status = status
        self.save()

    def get_items(self):
        return OrderedItem.objects.filter(delivery_group__order=self)

    def is_fully_paid(self):
        total_paid = sum([payment.total for payment in
                          self.payments.filter(status='confirmed')], Decimal())
        total = self.get_total()
        return total_paid >= total.gross

    def get_user_email(self):
        if self.user:
            return self.user.email
        return self.anonymous_user_email

    def __iter__(self):
        return iter(self.groups.all())

    def __repr__(self):
        return '<Order #%r>' % (self.id,)

    def __unicode__(self):
        return u'#%d' % (self.id, )

    @property
    def billing_full_name(self):
        return u'%s %s' % (self.billing_first_name, self.billing_last_name)

    def get_absolute_url(self):
        return reverse('order:details', kwargs={'token': self.token})

    def get_delivery_total(self):
        return sum([group.price for group in self.groups.all()],
                   Price(0, currency=settings.SATCHLESS_DEFAULT_CURRENCY))

    def send_confirmation_email(self):
        email = self.get_user_email()
        payment_url = build_absolute_uri(
            reverse('order:payment:index', kwargs={'token': self.token}))
        context = {'payment_url': payment_url}
        send_email(email, 'order/emails/confirm_email.txt', context)


class DeliveryGroup(Subtyped, ItemSet):
    STATUS_CHOICES = (
        ('new', pgettext_lazy(u'Delivery group status field value', u'New')),
        ('cancelled', pgettext_lazy(u'Delivery group status field value',
                                    u'Cancelled')),
        ('shipped', pgettext_lazy(u'Delivery group status field value',
                                  u'Shipped')))
    status = models.CharField(
        pgettext_lazy(u'Delivery group field', u'Delivery status'),
        max_length=32, default='new', choices=STATUS_CHOICES)
    order = models.ForeignKey(Order, related_name='groups', editable=False)
    price = PriceField(
        pgettext_lazy(u'Delivery group field', u'unit price'),
        currency=settings.SATCHLESS_DEFAULT_CURRENCY, max_digits=12,
        decimal_places=4,
        default=0,
        editable=False)

    def __repr__(self):
        return '%s(%r)' % (self.__class__.__name__, list(self))

    def __iter__(self):
        if self.id:
            return iter(self.items.select_related('product').all())
        return super(DeliveryGroup, self).__iter__()

    def change_status(self, status):
        self.status = status
        self.save()

    def get_total(self, **kwargs):
        return (super(DeliveryGroup, self).get_total(**kwargs) + self.price)

    def add_items_from_partition(self, partition):
        for item_line in partition:
            product_name = unicode(item_line.product)
            price = item_line.get_price_per_item()
            self.items.create(
                product=item_line.product,
                quantity=item_line.get_quantity(),
                unit_price_net=price.net,
                product_name=product_name,
                unit_price_gross=price.gross)


class ShippedDeliveryGroup(DeliveryGroup):

    address = models.ForeignKey(Address, related_name='+')

    def __unicode__(self):
        return u'Shipped delivery'


class DigitalDeliveryGroup(DeliveryGroup):

    email = models.EmailField()

    def __unicode__(self):
        return u'Digital delivery'


class OrderedItem(models.Model, ItemLine):

    delivery_group = models.ForeignKey(
        DeliveryGroup, related_name='items', editable=False)
    product = models.ForeignKey(
        Product, blank=True, null=True, related_name='+',
        on_delete=models.SET_NULL,
        verbose_name=pgettext_lazy(u'OrderedItem field', u'product'))
    product_name = models.CharField(
        pgettext_lazy(u'OrderedItem field', u'product name'), max_length=128)
    quantity = models.DecimalField(
        pgettext_lazy(u'OrderedItem field', u'quantity'),
        max_digits=10, decimal_places=4)
    unit_price_net = models.DecimalField(
        pgettext_lazy(u'OrderedItem field', u'unit price (net)'),
        max_digits=12, decimal_places=4)
    unit_price_gross = models.DecimalField(
        pgettext_lazy(u'OrderedItem field', u'unit price (gross)'),
        max_digits=12, decimal_places=4)

    def get_price_per_item(self, **kwargs):
        return Price(net=self.unit_price_net, gross=self.unit_price_gross,
                     currency=settings.SATCHLESS_DEFAULT_CURRENCY)

    def __unicode__(self):
        return self.product_name

    def get_quantity(self):
        return self.quantity

userprofile/forms.py
from django import forms
from django.contrib.auth.models import AnonymousUser

from .models import Address, AddressBook


class AddressForm(forms.ModelForm):

    class Meta:
        model = Address


class AddressBookForm(forms.ModelForm):

    class Meta:
        model = AddressBook
        fields = ['alias']

    def clean(self):
        super(AddressBookForm, self).clean()
        if AddressBook.objects.filter(
            user_id=self.instance.user_id, alias=self.cleaned_data.get('alias')
        ).exclude(address=self.instance.address_id).exists():
            self._errors['alias'] = self.error_class(
                ['You are already using such alias for another address'])

        return self.cleaned_data


class UserAddressesForm(forms.Form):

    address = forms.ModelChoiceField(queryset=AddressBook.objects.none(),
                                     required=False,
                                     empty_label='Enter below')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', AnonymousUser()) or AnonymousUser()
        super(UserAddressesForm, self).__init__(*args, **kwargs)
        address = self.fields['address']
        if user.is_authenticated():
            address.queryset = user.address_book.all()

order/views.py
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from order.models import Order


def success(request, token):
    order = get_object_or_404(Order, token=token)
    if order.status == 'fully-paid':
        return TemplateResponse(request, 'order/success.html',
                                {'order': order})
    return redirect('order:payment:index', token=order.token)


def details(request, token):
    order = get_object_or_404(Order, token=token)
    groups = order.groups.all()
    payments = order.payments.all()
    return TemplateResponse(request, 'order/details.html',
                            {'order': order, 'groups': groups,
                             'payments': payments})

userprofile/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST

from .models import AddressBook
from .forms import AddressBookForm, AddressForm


@login_required
def details(request):

    ctx = {'address_book': request.user.address_book.all()}
    return TemplateResponse(request, "userprofile/details.html", ctx)


@login_required
def orders(request):

    ctx = {'orders': request.user.orders.prefetch_related('groups')}
    return TemplateResponse(request, "userprofile/orders.html", ctx)


def validate_address_and_render(request, address_form, address_book_form,
                                success_message):
    if address_form.is_valid() and address_book_form.is_valid():
        address = address_form.save()
        address_book_form.instance.address = address
        address_book = address_book_form.save()
        messages.success(request, success_message % address_book)
        return HttpResponseRedirect(reverse("profile:details"))

    return TemplateResponse(
        request,
        "userprofile/address-edit.html",
        {'address_form': address_form, 'address_book_form': address_book_form})


@login_required
def address_edit(request, slug, pk):

    address_book = get_object_or_404(AddressBook, pk=pk, user=request.user)
    address = address_book.address

    if not address_book.get_slug() == slug and request.method == "GET":
        return HttpResponseRedirect(address_book.get_absolute_url())

    if request.POST:
        address_form = AddressForm(request.POST, instance=address)
        address_book_form = AddressBookForm(
            request.POST, instance=address_book)
    else:
        address_form = AddressForm(instance=address)
        address_book_form = AddressBookForm(instance=address_book)

    message = "Successfully updated address '%s'."

    return validate_address_and_render(
        request, address_form, address_book_form, success_message=message)


@login_required
def address_create(request):

    if request.POST:
        address_form = AddressForm(request.POST)
        address_book_form = AddressBookForm(
            request.POST, instance=AddressBook(user=request.user))
    else:
        address_form = AddressForm()
        address_book_form = AddressBookForm()

    message = "Successfully created address '%s'."

    return validate_address_and_render(
        request, address_form, address_book_form, success_message=message)


@login_required
def address_delete(request, slug, pk):

    address_book = get_object_or_404(AddressBook, pk=pk, user=request.user)

    if not address_book.get_slug() == slug:
        raise Http404

    if request.POST:
        address_book.address.delete()
        message = "Successfully deleted address '%s'."
        messages.success(request, message % address_book)
        return HttpResponseRedirect(reverse("profile:details"))

    return TemplateResponse(request, "userprofile/address-delete.html")


@login_required
@require_POST
def address_make_default(request, pk, purpose):
    user = request.user

    address_book = get_object_or_404(AddressBook, pk=pk, user=user)

    if purpose == 'shipping':
        user.default_shipping_address = address_book
    elif purpose == 'billing':
        user.default_billing_address = address_book
    else:
        raise AssertionError(
            "``purpose`` should be ``billing`` or ``shipping``")

    user.save()

    return redirect('profile:details')

userprofile/templates/userprofile/address-delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ block.super }} » {% trans "Delete Address" %}{% endblock %}

{% block content %}
    <div>
        Are you sure?
        <form action="." method="post">
            {% csrf_token %}
            <button type="submit" class="btn">Delete</button>
            <a href="{% url 'profile:details' %}" class="btn">Cancel</a>
        </form>
    </div>
{% endblock content %}

userprofile/templates/userprofile/address-edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ block.super }} » {% trans "Edit Address" %}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
<li>
    <a href="{% url 'profile:details' %}">{% trans "Your profile" %}</a> <span class="divider">/</span>
</li>
<li>
    <a href=".">{% trans "Edit address" %}</a> <span class="divider">/</span>
</li>
{% endblock breadcrumb %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {% if address_form.errors or address_book_form.errors %}
            <div class="alert alert-error">
                Please correct errors below.
            </div>
        {% endif %}
        <fieldset>
            <legend>Address</legend>
            {% with form=address_book_form %}
                {% include 'saleor/partials/form.html' %}
            {% endwith %}
            {% with form=address_form %}
                {% include 'saleor/partials/form.html' %}
            {% endwith %}
        </fieldset>
        <button type="submit" class="btn">Save</button>
    </form>
{% endblock content %}

userprofile/templates/userprofile/details.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ block.super }} » {% trans "User profile" %}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
<li>
    <a href="{% url 'profile:details' %}">{% trans "Your profile" %}</a> <span class="divider">/</span>
</li>
{% endblock breadcrumb %}

{% block content %}
    <ul>
    {% for entry in address_book %}
        <li>
            <p>
                {{ entry }}
                {% if user.default_shipping_address == entry and user.default_billing_address == entry %}
                    {% trans "(default for billing and shipping)" %}
                {% elif user.default_shipping_address == entry %}
                    {% trans "(default for shipping)" %}
                {% elif user.default_billing_address == entry %}
                    {% trans "(default for billing)" %}
                {% endif %}
            </p>
            <div class="row">
                <div class="span">
                    <a href="{% url 'profile:address-edit' pk=entry.pk slug=entry.get_slug %}" class="btn">{% trans "Edit" %}</a>
                </div>
                <div class="span">
                    <form method="post" action="{% url "profile:address-make-default" pk=entry.pk purpose="shipping" %}" class="form-inline form-horizontal">
                        {% csrf_token %}
                        <input type="submit" value="{% trans "Make default for shipping" %}" class="btn">
                    </form>
                </div>
                <div class="span">
                    <form method="post" action="{% url "profile:address-make-default" pk=entry.pk purpose="billing" %}" class="form-inline form-horizontal">
                        {% csrf_token %}
                        <input type="submit" value="{% trans "Make default for billing" %}" class="btn">
                    </form>
                </div>
                <div class="span">
                    <a href="{% url 'profile:address-delete' pk=entry.pk slug=entry.get_slug %}" class="btn">{% trans "Delete" %}</a>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>

    <div>
        <a href="{% url 'profile:address-create' %}" class="btn">{% trans "Add new address" %}</a>
    </div>
    <div>
        <a href="{% url 'registration:request_email_change' %}">{% trans 'Change your email address' %}</a>
    </div>
    <div>
        <a href="{% url 'registration:change_password' %}">{% trans 'Change password' %}</a>
    </div>


{% endblock content %}

userprofile/templates/userprofile/orders.html
{% extends "base.html" %}
{% load i18n %}
{% load gross from prices %}

{% block breadcrumb %}
    {{ block.super }}
<li>
    <a href="{% url 'profile:orders' %}">{% trans "Your orders" %}</a> <span class="divider">/</span>
</li>
{% endblock breadcrumb %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>
                    {% trans "Order" %}
                </th>
                <th>
                    {% trans "Price" %}
                </th>
                <th>
                    {% trans "Date" %}
                </th>
                <th>
                    {% trans "Last status change" %}
                </th>
                <th>
                    {% trans "Status" %}
                </th>
                <th>
                    <!-- details link -->
                </th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td>
                        {{ order }}
                    </td>
                    <td>
                        {% gross order.get_total %}
                    </td>
                    <td>
                        {{ order.created }}
                    </td>
                    <td>
                        {{ order.last_status_change }}
                    </td>
                    <td>
                        {{ order.get_status_display }}
                    </td>
                    <td>
                        <a href="{{ order.get_absolute_url }}">{% trans "See details" %}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}